### ISSUE TITLE
Pretty Print

### ISSUE THREAD

**Issue by tp** [zhengxiaoyao0716/dart_easy_json#2]
Hey,

I am using your library in testing scenarios, where I want to dump object trees for snapshot-like comparisons.

What would really help there is pretty printing.

Do you think that is feasible to add here?

**Comment by zhengxiaoyao0716** [comment]
![image](https://user-images.githubusercontent.com/12682063/55494036-9f43fb00-566c-11e9-8e8a-ad98485d5cf0.png)
How about that you think?

**Comment by tp** [comment]
@zhengxiaoyao0716 That looks good.

From the web's `JSON.stringify` I am used to put in a `number` representing the white-space characters, so no other indentation is possible.

I think that is the common case, but it also wouldn't be harder to put `'  '` in here.

Your call :)

**Comment by zhengxiaoyao0716** [comment]
Thanks, as the `JsonEncoder.withIndent` method of `Dart` used string indent style, I think it's better to keep consistent with it. In addition, The third argument `space` of the  `JSON.stringify`  method is can both be [a number or a string](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#Parameters). So I decision to keep using string indent style.

**Comment by tp** [comment]
Just tried it out, very nice :) Thanks!
